language: python

python:
  - "2.6"
  - "2.7"
  - "3.3"

env:
  - DJANGO=Django==1.4.21
  - DJANGO=Django==1.7.9
  - DJANGO=Django==1.8.3

matrix:
  allow_failures:
    # Allow failures for Python 3.3
    - python: "3.3"
    # 1.8 is not (yet) officially supported
    - env: DJANGO=Django==1.8.3
  exclude:
    # Django 1.4 and 1.5 do not fully support Python 3.3
    - env: DJANGO=Django==1.4.21
      python: "3.3"
    # 1.7 and 1.8 don't support Python 2.6 anymore
    - env: DJANGO=Django==1.7.9
      python: "2.6"
    - env: DJANGO=Django==1.8.3
      python: "2.6"

# command to install dependencies
install:
  - pip install $DJANGO
  - pip install -r requirements.txt

# command to run tests
script: python setup.py test
