language: python

python:
  - "2.5"
  - "2.6"
  - "2.7"

env:
  - DJANGO=Django==1.4.5
  - DJANGO=Django==1.5.1

matrix:
  exclude:
    # Django 1.5 drops support for Python 2.5
   - python: "2.5"
     env: DJANGO=Django==1.5.1
  allow_failures:
    # Failing due to Django 1.5 dropping CBV support
    - env: DJANGO=Django==1.5.1

# command to install dependencies
install:
  - pip install -q $DJANGO --use-mirrors
  - pip install -r requirements.txt --use-mirrors

# command to run tests
script: python setup.py test
