language: python

python:
  - "2.5"
  - "2.6"
  - "2.7"

env:
  - DJANGO=Django==1.3.7
  - DJANGO=Django==1.4.5
  - DJANGO=https://www.djangoproject.com/download/1.5b2/tarball/

matrix:
  exclude:
    # Django 1.5 drops support for Python 2.5
   - python: "2.5"
     env: DJANGO=https://www.djangoproject.com/download/1.5b2/tarball/
  allow_failures:
    # Failing due to Django 1.5 dropping CBV support
    - env: DJANGO=https://www.djangoproject.com/download/1.5c2/tarball/

# command to install dependencies
install:
  - pip install -q $DJANGO --use-mirrors
  - pip install -r requirements.txt --use-mirrors
  - pip install -q https://github.com/praekelt/django-setuptest/archive/f4eacb4a929cdcc853a5c053c282dada5bdedc99.tar.gz --use-mirrors

# command to run tests
script: python setup.py test
