language: python

sudo: false

python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6
  - 3.7

env:
  - DJANGO="Django<1.12"    # Django 1.11.x
  - DJANGO="Django<2.1"     # Django 2.0.x
  - DJANGO="Django==2.1b1"  # Django 2.1b

cache:
  directories:
    - $HOME/.cache/pip

matrix:
  exclude:
    # Only supported Python/Django combinations
    - env: DJANGO="Django<2.1"
      python: 2.7
    - env: DJANGO="Django==2.1b1"
      python: 2.7
    - env: DJANGO="Django==2.1b1"
      python: 3.4
    - env: DJANGO="Django<1.12"
      python: 3.7

  allow_failures:
    - env: DJANGO="Django==2.1b1"

# command to install dependencies
install:
  # Latest PIP uses wheel by default
  - pip install --upgrade pip
  - pip install $DJANGO
  - pip install -r requirements.txt
  - pip install -r requirements_test.txt
  - pip install coveralls

# command to run tests
script: coverage run setup.py test

after_success:
  coveralls
