language: python

python:
# Disable 2.5 for now due to a bug in django-setuptest
# Ref: https://github.com/praekelt/django-setuptest/pull/6
#  - "2.5" 
  - "2.6"
  - "2.7"

env:
  - DJANGO_VERSION=1.3.4
  - DJANGO_VERSION=1.4.2

# command to install dependencies
install:
  - pip install -q Django==$DJANGO_VERSION --use-mirrors
  - pip install -r requirements.txt --use-mirrors

# command to run tests
script: python setup.py test
